AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/*/*spec.rb'
    - 'codebreaker.gemspec'
